name: angiang_lens
description: AnGiang Lens - nhận diện địa điểm du lịch bằng AI offline.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.12.1
  image_picker: ^1.2.3
  image: ^4.9.1
  flutter_tts: ^4.2.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ai/angiang_lens_model.tflite
    - assets/ai/angiang_lens_database.json
    - assets/content/place_catalog.json
    - assets/places/Mieu_bcx/
    - assets/places/ho_PT/
    - assets/places/den_NTT/
    - assets/places/Phu_quoc/
    - assets/places/Thach_Dong/
    - assets/places/Chua_Ta_Pa/
    - assets/places/Tra_Su/
    - assets/places/Nui_Cam/
    - assets/icon/app_icon.png
flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
